url: 'https://studio-feiler.com'
baseurl: ''
title: 'studio feiler âœ· Nachhaltige und barrierefreie Gestaltung'

author:
  name: 'Annabelle Feiler'

highlighter: rouge # code highlighter for markdown

collections:
  leistungen:
  projekte:
    output: true
    permalink: /projekt/:name/
  cv:
